version: '3.8'
services:
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - app-network

  frontend:
    image: ghcr.io/codeowlcove/homepage_frontend:main
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=https://backend.codeowlcove.com

  backend:
    image: ghcr.io/codeowlcove/homepage_backend:main
    expose:
      - "8080"
    networks:
      - app-network
    environment:
      - BACKEND_PORT=8080
      - MYSQL_HOST=db
      - MYSQL_DATABASE=twitchplays
      - MYSQL_DB_USERNAME=backend_db_client
      - MYSQL_DB_PASSWORD=proneraggedyplanetgallows
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=proneraggedyplanetgallows
      - MYSQL_ROOT_HOST='%'
      - MYSQL_DATABASE=twitchplays
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_USER=backend_db_client
      - MYSQL_PASSWORD=proneraggedyplanetgallows
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  caddy-data:
  caddy-config: