name: Build and Dockerize

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: "temurin"
    - name: Checkout project sources
      uses: actions/checkout@v4
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag homepage_backend_app:$(date +%s)
