name: Build and Dockerize

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Install Dependencies
      run: ./gradlew install
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag homepage_backend_app:$(date +%s)
